version: '3.7'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/sites-available/default
    depends_on:
      - app
  app:
    image: node:12
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
